"""
Autogenerated python message buffer code.
Source: /Users/Ben.Gabaldon/victor/robot/clad/src/clad/audio/audioStateTypes.clad
Full command line: victor-clad/tools/message-buffers/emitters/Python_emitter.py robot/clad/src/clad/audio/audioStateTypes.clad
"""

from __future__ import absolute_import
from __future__ import print_function

def _modify_path():
  import inspect, os, sys
  search_paths = [
    'Ben.Gabaldon/victor/-',
    'Ben.Gabaldon/victor/victor-clad/tools/message-buffers/support/python',
  ]
  currentpath = os.path.abspath(os.path.dirname(inspect.getfile(inspect.currentframe())))
  for search_path in search_paths:
    search_path = os.path.normpath(os.path.abspath(os.path.realpath(os.path.join(currentpath, search_path))))
    if search_path not in sys.path:
      sys.path.insert(0, search_path)
_modify_path()

import msgbuffers

Anki = msgbuffers.Namespace()
Anki.AudioMetaData = msgbuffers.Namespace()
Anki.AudioMetaData.GameState = msgbuffers.Namespace()

class GenericState(object):
  "Automatically-generated uint_32 enumeration."
  Invalid = 0

Anki.AudioMetaData.GameState.GenericState = GenericState
del GenericState


class Mood(object):
  "Automatically-generated uint_32 enumeration."
  Angry     = 1206605712
  Curious   = 620622945
  Happy     = 1427264549
  Invalid   = 0
  Neutral   = 670611050
  Sad       = 443572635
  Surprised = 2662801688

Anki.AudioMetaData.GameState.Mood = Mood
del Mood


class Robot_Alexa_Locale(object):
  "Automatically-generated uint_32 enumeration."
  En_Au   = 1906015505
  En_De   = 1855682766
  En_Fr   = 1889237923
  En_Uk   = 2107346979
  En_Us   = 2107347003
  Invalid = 0

Anki.AudioMetaData.GameState.Robot_Alexa_Locale = Robot_Alexa_Locale
del Robot_Alexa_Locale


class Robot_Vic_External_Language(object):
  "Automatically-generated uint_32 enumeration."
  English  = 3383237639
  French   = 3133094709
  German   = 4290373403
  Invalid  = 0
  Japanese = 2008704848

Anki.AudioMetaData.GameState.Robot_Vic_External_Language = Robot_Vic_External_Language
del Robot_Vic_External_Language


class Robot_Vic_External_Processing(object):
  "Automatically-generated uint_32 enumeration."
  Invalid                           = 0
  Robot_Vic_External_Processed      = 1575276615
  Robot_Vic_External_Unit_Test_Mock = 203897895
  Robot_Vic_External_Unprocessed    = 3289079812

Anki.AudioMetaData.GameState.Robot_Vic_External_Processing = Robot_Vic_External_Processing
del Robot_Vic_External_Processing


class Robot_Vic_Low_Power_Mode(object):
  "Automatically-generated uint_32 enumeration."
  Invalid            = 0
  Low_Power_Mode_Off = 3340184725
  Low_Power_Mode_On  = 1712112425

Anki.AudioMetaData.GameState.Robot_Vic_Low_Power_Mode = Robot_Vic_Low_Power_Mode
del Robot_Vic_Low_Power_Mode


class Robot_Vic_Petting_Level(object):
  "Automatically-generated uint_32 enumeration."
  Invalid                    = 0
  Robot_Vic_Petting_Level_01 = 4289156881
  Robot_Vic_Petting_Level_02 = 4289156882
  Robot_Vic_Petting_Level_03 = 4289156883
  Robot_Vic_Petting_Level_04 = 4289156884

Anki.AudioMetaData.GameState.Robot_Vic_Petting_Level = Robot_Vic_Petting_Level
del Robot_Vic_Petting_Level


class Robot_Vic_Quiet(object):
  "Automatically-generated uint_32 enumeration."
  Invalid             = 0
  Robot_Vic_Quiet_Off = 2503617831
  Robot_Vic_Quiet_On  = 3604654675

Anki.AudioMetaData.GameState.Robot_Vic_Quiet = Robot_Vic_Quiet
del Robot_Vic_Quiet


class Robot_Vic_System_Tests(object):
  "Automatically-generated uint_32 enumeration."
  App_Run   = 2777662008
  Invalid   = 0
  Unit_Test = 522293050

Anki.AudioMetaData.GameState.Robot_Vic_System_Tests = Robot_Vic_System_Tests
del Robot_Vic_System_Tests


class Robot_Vic_Vc(object):
  "Automatically-generated uint_32 enumeration."
  Invalid          = 0
  Robot_Vic_Vc_Off = 1551477384
  Robot_Vic_Vc_On  = 3189356050

Anki.AudioMetaData.GameState.Robot_Vic_Vc = Robot_Vic_Vc
del Robot_Vic_Vc


class Robot_Vic_Volume(object):
  "Automatically-generated uint_32 enumeration."
  High       = 3550808449
  Invalid    = 0
  Low        = 545371365
  Medium     = 2849147824
  Mediumhigh = 3176515060
  Mediumlow  = 1216798262
  Mute       = 2974103762

Anki.AudioMetaData.GameState.Robot_Vic_Volume = Robot_Vic_Volume
del Robot_Vic_Volume


class StateGroupType(object):
  "Automatically-generated uint_32 enumeration."
  Invalid                       = 0
  Mood                          = 3128647864
  Robot_Alexa_Locale            = 1812603720
  Robot_Vic_External_Language   = 2984487667
  Robot_Vic_External_Processing = 475135532
  Robot_Vic_Low_Power_Mode      = 1633231277
  Robot_Vic_Petting_Level       = 3399985269
  Robot_Vic_Quiet               = 3765614597
  Robot_Vic_System_Tests        = 1822792682
  Robot_Vic_Vc                  = 3929179650
  Robot_Vic_Volume              = 3279659965

Anki.AudioMetaData.GameState.StateGroupType = StateGroupType
del StateGroupType


